# Generated by Django 5.2 on 2025-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(help_text='Height in centimeters (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms (kg)'),
        ),
    ]
