# Generated by Django 5.2 on 2025-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthentry',
            name='doctor_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthentry',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
